{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "p_l1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"iot_measurement\" and\r\n    r._field == \"p_l1\"\r\n  )"
    }
   ]
  },
  {
   "title": "P l2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"iot_measurement\" and\r\n    r._field == \"p_l2\"\r\n  )"
    }
   ]
  },
  {
   "title": "P l3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"iot_measurement\" and\r\n    r._field == \"p_l3\"\r\n  )"
    }
   ]
  }
 ]
}